#!/bin/bash
# nemotron winner: baseline — 123.6 t/s
# generated by autoresearch-nemotron 2026-05-21
export LD_LIBRARY_PATH=/home/dino/llama.cpp/build-cuda128-clean/bin
exec /home/dino/llama.cpp/build-cuda128-clean/bin/llama-server \
  --model /home/dino/models/Nemotron-3-Nano-30B-A3B/nvidia_Nemotron-3-Nano-30B-A3B-Q4_K_M.gguf \
  --host 0.0.0.0 --port 8022 \
  --n-gpu-layers 999 \
  --ctx-size 32768 \
  --threads 8 \
  --cache-ram 0
